### ISSUE TITLE
error while run on windows 

### ISSUE THREAD

**Issue by rashedomar** [FOSSEE/online_test#662]
can you make a documentation for run the app on windows and  heroku!  

````
path/online_test>invoke start
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\invoke.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\program.py", line 293, in run
    self.execute()
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\program.py", line 414, in execute
    executor.execute(*self.tasks)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
  File "C:\Users\rashed\Desktop\education\online_test\tasks.py", line 122, in start
    getimage(ctx, image=SRC_IMAGE_NAME)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
  File "C:\Users\rashed\Desktop\education\online_test\tasks.py", line 84, in getimage
    ctx.run(cmd, hide=True)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\context.py", line 82, in run
    return self._run(runner, command, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\context.py", line 89, in _run
    return runner.run(command, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\runners.py", line 262, in run
    return self._run_body(command, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\runners.py", line 276, in _run_body
    self.start(command, shell, env)
  File "c:\program files (x86)\python38-32\lib\site-packages\invoke\runners.py", line 974, in start
    self.process = Popen(
  File "c:\program files (x86)\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\program files (x86)\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 3] The system cannot find the path specified
````

**Comment by adityacp** [comment]
Currently, there is no windows support for the project.
